# Generated by Django 4.1.7 on 2023-03-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField(blank=True)),
                ('area', models.FloatField(blank=True)),
                ('countrys', models.PositiveSmallIntegerField(blank=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(blank=True, max_length=50)),
                ('nation', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('population', models.IntegerField(blank=True)),
                ('area', models.FloatField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, default='+', max_length=5)),
                ('time_zone', models.CharField(blank=True, choices=[('-12', '-12'), ('-11', '-11'), ('-10', '-10'), ('-8', '-8'), ('-7', '-7'), ('-6', '-6'), ('-5', '-5'), ('-4', '-4'), ('-3', '-3'), ('-2', '-2'), ('-1', '-1'), ('+0', '+0'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4'), ('+5', '+5'), ('+6', '+6'), ('+7', '+7'), ('+8', '+8'), ('+10', '+10'), ('+11', '+11'), ('+12', '+12')], max_length=3)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('government_type', models.CharField(blank=True, choices=[('Republic', 'Republic'), ('Monarchy', 'Monarchy'), ('State', 'State'), ('Federation', 'Federation'), ('Emirate', 'Emirate'), ('Kingdom', 'Kingdom'), ('Empire', 'Empire'), ('Theocracy', 'Theocracy')], max_length=50)),
                ('climate', models.TextField(blank=True, max_length=1000)),
                ('urbanization', models.FloatField(blank=True)),
                ('average_age', models.PositiveSmallIntegerField(blank=True)),
                ('flag', models.ImageField(blank=True, upload_to='flags')),
                ('emblem', models.ImageField(blank=True, upload_to='emblems')),
                ('hymn', models.TextField(blank=True)),
                ('continent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Contiguous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contiguous_countries', to='mainApp.country')),
                ('countrys', models.ManyToManyField(related_name='contiguous_to', to='mainApp.country')),
            ],
        ),
    ]
