# Generated by Django 4.1.7 on 2023-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_country_emblem_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='average_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='climate',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='government_type',
            field=models.CharField(blank=True, choices=[('Republic', 'Republic'), ('Islamic Republic', 'Islamic Republic'), ('Monarchy', 'Monarchy'), ('State', 'State'), ('Federation', 'Federation'), ('Emirate', 'Emirate'), ('Kingdom', 'Kingdom'), ('Empire', 'Empire'), ('Theocracy', 'Theocracy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='hymn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone',
            field=models.CharField(blank=True, default='+', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('-12', '-12'), ('-11', '-11'), ('-10', '-10'), ('-8', '-8'), ('-7', '-7'), ('-6', '-6'), ('-5', '-5'), ('-4', '-4'), ('-3', '-3'), ('-2', '-2'), ('-1', '-1'), ('+0', '+0'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4'), ('+5', '+5'), ('+6', '+6'), ('+7', '+7'), ('+8', '+8'), ('+10', '+10'), ('+11', '+11'), ('+12', '+12')], max_length=3, null=True),
        ),
    ]
